### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by vishalj254** [DREDNES/video-chat-roulette#1]
Working on localhost
but not working on live server

**Comment by nrkvg** [comment]
What you mean saying live server? 
It is node-based server application, so you should run it by node and use localhost
If I understand you correct, live server is only hosts static pages, without node.js server

If you are talking about server, where demo runs, it is okey, heroku works fine

Maybe you tried to connect from client on localhost to client on heroku?

**Comment by vishalj254** [comment]
Live server means that not working on my own server but run on localhost

**Comment by nrkvg** [comment]
oh, the problem is that I don't have own server and can't test it on it. If you could find out what is the problem, you can help to fix it
